name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Updates every day
  workflow_dispatch:               # Allow manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: c0dewithLokesh
          template: classic
          base: header, activity, community
          config_timezone: Asia/Kolkata
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_repositories: yes
          config_display: large
          config_order: base.header, base.activity, followup, languages, achievements
